version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - nuxt
    restart: always
    networks:
      - canfly-network
  
  nuxt:
    build:
      context: ./nuxt-app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"
    restart: always
    networks:
      - canfly-network
    volumes:
      - ./nuxt-app:/app
      - nuxt_node_modules:/app/node_modules

  # Дополнительные сервисы при необходимости, например:
  # - Redis для кэширования
  # - PostgreSQL или другая БД для данных
  # - и т.д.

networks:
  canfly-network:
    driver: bridge

volumes:
  nuxt_node_modules: 