version: '3'

services:
  logs-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - LOG_STORAGE_DIR=/app/logs
      - API_KEY=dev-api-key-for-testing
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped 